Update temp.yml

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -30,10 +30,9 @@ jobs:
             mihomo_exe="mihomo.exe"
           fi
 
-          wget https://github.com/2dust/v2rayN/releases/download/6.${version}/v2rayN-With-Core.zip 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
-          cat error.log
+          wget -q https://github.com/2dust/v2rayN/releases/download/6.${version}/v2rayN-With-Core.zip || true
+          unzip v2rayN-With-Core.zip > /dev/null 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
           if [ ! -s error.log ]; then
-            unzip -q v2rayN-With-Core.zip
             if [ "$version" -gt 32 ]; then
               echo -e "\033[32mwine ${GITHUB_WORKSPACE}/v2rayN-With-Core/bin/mihomo/mihomo.exe -v:\033[0m"
               wine ${GITHUB_WORKSPACE}/v2rayN-With-Core/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
@@ -48,9 +47,9 @@ jobs:
             echo -e "\033[32m--------------------------------------------------------------------------------\033[0m"
           fi
 
-          wget https://github.com/2dust/v2rayN/releases/download/6.${version}/zz_v2rayN-With-Core-SelfContained.7z 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          wget -q https://github.com/2dust/v2rayN/releases/download/6.${version}/zz_v2rayN-With-Core-SelfContained.7z || true
+          7z x zz_v2rayN-With-Core-SelfContained.7z > /dev/null 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
           if [ ! -s error.log ]; then
-            7z x zz_v2rayN-With-Core-SelfContained.7z > /dev/null
             echo -e "\033[35mzz_v2rayN-With-Core-SelfContained:\033[0m"
             if [ "$version" -gt 32 ]; then
               echo -e "\033[32mwine ${GITHUB_WORKSPACE}/zz_v2rayN-With-Core-SelfContained/bin/mihomo/mihomo.exe -v:\033[0m"
