Update temp.yml

diff --git a/.github/workflows/temp.yml b/.github/workflows/temp.yml
--- a/.github/workflows/temp.yml
+++ b/.github/workflows/temp.yml
@@ -23,12 +23,12 @@ jobs:
         sudo apt update &> /dev/null
         sudo apt install -y wine &> /dev/null
         for ((minor=22; minor<=44; minor++)); do
-          if ! wget -nv https://github.com/v2fly/v2ray-core/releases/download/v4.${minor}.0/v2ray-linux-64.zip 2> error.log; then
+          if ! wget -nv https://github.com/v2fly/v2ray-core/releases/download/v4.${minor}.0/v2ray-windows-64.zip 2> error.log; then
             perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
             continue
           fi
-          unzip -q v2ray-linux-64.zip
-          echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2ray-linux-64/v2ray.exe -help:${RESET}"
-          wine ${GITHUB_WORKSPACE}/v2ray-linux-64/v2ray.exe -help 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
-          rm -rf v2ray-linux-64.zip v2ray-linux-64
+          unzip -q -d ${GITHUB_WORKSPACE}/temp v2ray-windows-64.zip
+          echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/temp/v2ray.exe -help:${RESET}"
+          wine ${GITHUB_WORKSPACE}/temp/v2ray.exe -help 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          rm -rf v2ray-windows-64.zip temp
         done
