Update v2rayN-version.yml

diff --git a/.github/workflows/v2rayN-version.yml b/.github/workflows/v2rayN-version.yml
--- a/.github/workflows/v2rayN-version.yml
+++ b/.github/workflows/v2rayN-version.yml
@@ -20,7 +20,7 @@ jobs:
         set -e
         sudo dpkg --add-architecture i386
         sudo apt update &> /dev/null
-        sudo apt install -y wine &> /dev/null
+        sudo apt install -y wget unzip wine &> /dev/null
         for ((minor=30; minor<=53; minor++)); do
           echo -e "${PURPLE}-------------------------------- 2.${minor} --------------------------------${RESET}"
           if ! wget -nv https://github.com/2dust/v2rayN/releases/download/2.${minor}/v2rayN-Core.zip 2> error.log; then
@@ -42,7 +42,7 @@ jobs:
         set -e
         sudo dpkg --add-architecture i386
         sudo apt update &> /dev/null
-        sudo apt install -y wine &> /dev/null
+        sudo apt install -y wget unzip wine &> /dev/null
         for ((minor=0; minor<=29; minor++)); do
           echo -e "${PURPLE}-------------------------------- 3.${minor} --------------------------------${RESET}"
           if [ "${minor}" -eq 15 ]; then
@@ -76,7 +76,7 @@ jobs:
         set -e
         sudo dpkg --add-architecture i386
         sudo apt update &> /dev/null
-        sudo apt install -y wine &> /dev/null
+        sudo apt install -y wget unzip wine &> /dev/null
         for ((minor=0; minor<=36; minor++)); do
           echo -e "${PURPLE}-------------------------------- 4.${minor} --------------------------------${RESET}"
           if ! wget -nv https://github.com/2dust/v2rayN/releases/download/4.${minor}/v2rayN-Core.zip 2> error.log; then
@@ -102,7 +102,7 @@ jobs:
         set -e
         sudo dpkg --add-architecture i386
         sudo apt update &> /dev/null
-        sudo apt install -y wine &> /dev/null
+        sudo apt install -y wget unzip wine &> /dev/null
         for ((minor=0; minor<=39; minor++)); do
           echo -e "${PURPLE}-------------------------------- 5.${minor} --------------------------------${RESET}"
           if ! wget -nv https://github.com/2dust/v2rayN/releases/download/5.${minor}/v2rayN-Core.zip 2> error.log; then
@@ -131,7 +131,7 @@ jobs:
       run: |
         set -e
         sudo apt update &> /dev/null
-        sudo apt install -y 7zip wine &> /dev/null
+        sudo apt install -y wget unzip 7zip wine &> /dev/null
         for ((minor=0; minor<=60; minor++)); do
           echo -e "${PURPLE}-------------------------------- 6.${minor} --------------------------------${RESET}"
           if [ "${minor}" -lt 2 ]; then
@@ -198,4 +198,94 @@ jobs:
             wine ${GITHUB_WORKSPACE}/zz_v2rayN-With-Core-SelfContained/bin/Xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
             rm -rf zz_v2rayN-With-Core-SelfContained zz_v2rayN-With-Core-SelfContained.7z
           fi
+        done
+
+  v2rayN-7:
+    runs-on: ubuntu-latest
+    steps:
+    - name: v2rayN 7
+      run: |
+        set -e
+        sudo apt-get update &> /dev/null
+        sudo apt-get install -y wget unzip wine &> /dev/null
+        declare -a patch=([0]=9 [1]=3 [2]=3 [3]=2 [4]=2 [5]=6 [6]=2 [7]=1 [8]=3 [9]=3
+                           [10]=5 [11]=3 [12]=7 [13]=8 [14]=12 [15]=7 [16]=9 [17]=3 [18]=0
+        )
+        for minor in "${!patch[@]}"; do
+          echo -e "${PURPLE}-------------------------------- v2rayN 7.${minor}.${patch[$minor]} --------------------------------${RESET}"
+          if [ "$minor" -ge 14 ]; then
+            mihomo_exe="mihomo.exe"
+          else
+            mihomo_exe="mihomo-windows-amd64-compatible.exe"
+          fi
+          if [ "$minor" -lt 7 ]; then
+            wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64-With-Core.zip
+            unzip -q v2rayN-windows-64-With-Core.zip
+            echo -e "${PURPLE}v2rayN-windows-64-With-Core:RESET"
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/mihomo/${mihomo_exe} -v:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/sing_box/sing-box.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/xray/xray.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-With-Core/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            if [ "$minor" -lt 5 ]; then
+              wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64-SelfContained-With-Core.7z
+              7z x v2rayN-windows-64-SelfContained-With-Core.7z > /dev/null
+            else
+              wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64-SelfContained-With-Core.zip
+              unzip -q v2rayN-windows-64-SelfContained-With-Core.zip
+            fi
+            echo -e "${PURPLE}v2rayN-windows-64-SelfContained-With-Core:RESET"
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/mihomo/${mihomo_exe} -v:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/sing_box/sing-box.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/xray/xray.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained-With-Core/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          else
+            wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64.zip
+            unzip -q v2rayN-windows-64.zip
+            echo -e "${PURPLE}v2rayN-windows-64:RESET"
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/mihomo/${mihomo_exe} -v:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/sing_box/sing-box.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/xray/xray.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            if [ "$minor" -lt 18 ]; then
+              wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64-SelfContained.zip
+              unzip -q v2rayN-windows-64-SelfContained.zip
+              echo -e "${PURPLE}v2rayN-windows-64-SelfContained:RESET"
+              echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/mihomo/${mihomo_exe} -v:RESET"
+              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+              echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/sing_box/sing-box.exe version:RESET"
+              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+              echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/xray/xray.exe version:RESET"
+              wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-SelfContained/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            fi
+          fi
+          if [ "$minor" -ge 9]; then
+            wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-windows-64-desktop.zip
+            unzip -q v2rayN-windows-64-desktop.zip
+            mv ${GITHUB_WORKSPACE}/v2rayN-windows-64 ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop
+            echo -e "${PURPLE}v2rayN-windows-64-desktop:RESET"
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/mihomo/${mihomo_exe} -v:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/mihomo/${mihomo_exe} -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/sing_box/sing-box.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/sing_box/sing-box.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+            echo -e "${GREEN}wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/xray/xray.exe version:RESET"
+            wine ${GITHUB_WORKSPACE}/v2rayN-windows-64-desktop/bin/xray/xray.exe version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          fi
+          wget -nv https://github.com/2dust/v2rayN/releases/download/7.${minor}.${patch[$minor]}/v2rayN-linux-64.zip
+          unzip -q v2rayN-linux-64.zip
+          echo -e "${PURPLE}v2rayN-linux-64:RESET"
+          chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo
+          echo -e "${GREEN}${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo -v:RESET"
+          ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/mihomo/mihomo -v 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box
+          echo -e "${GREEN}${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box version:RESET"
+          ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/sing_box/sing-box version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
+          chmod +x ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray
+          echo -e "${GREEN}${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray version:RESET"
+          ${GITHUB_WORKSPACE}/v2rayN-linux-64/bin/xray/xray version 2> error.log || perl -pe 'print "\e[31m"; s/$/\e[0m/' error.log
         done
